### ISSUE TITLE
Code transformation

### ISSUE THREAD

**Issue by om198** [gmai2006/grammar#1]
My main goal is transformation from AST to new language –Java/ C#/ Type Script...
I have not found whole example using your advice (ST +Visitor).
Can you attach an example for me?

**Comment by gmai2006** [comment]
Since PB transformation is one of our beta products I cannot disclose but here are examples of a visitor and StringTemplate for generating a React page from the DataWindow model
`table(uri, functionName, cols) ::= <<
import React, { useCallback } from 'react';
import ReactDataGrid from '@inovua/reactdatagrid-community';
import '@inovua/reactdatagrid-community/index.css';

const gridStyle = { minHeight: 550 \}

$table_columns(cols)$

const loadData = () => {
  return fetch('$uri$',{
    headers : {
      'Content-Type': 'application/json',
      'Accept': 'application/json'
     }
  }).then(response => {
    return response.json().then(data => {
      console.log(data);
      return data;
    })
  })
}`

Example of using Visitor to extract SQL statement from DataWindow
`public class DataWindow2SqlTransformerVisitor extends DataWindowBaseVisitor<Void> {

  String sql = null;

  @Override
  public Void visitTable_decl(DataWindowParser.Table_declContext ctx) {
    if (!ctx.retrieve().isEmpty()) {
      final DataWindowParser.RetrieveContext retrieve = ctx.retrieve(0);
      sql = retrieve.DQUOTED_STRING().getText();
      sql = sql.substring(1, sql.length() - 1);
    } else if (!ctx.procedure().isEmpty()) {
      DataWindowParser.ProcedureContext procedure = ctx.procedure(0);
      sql = procedure.DQUOTED_STRING().getText();
      sql = sql.substring(1, sql.length() - 1);
    }
    return null;
  }

  public String getSql() {
    return sql;
  }
}`

**Comment by gmai2006** [comment]
Good luck with what you are doing.

**Comment by gmai2006** [comment]
Question about BP transformation has been addressed
